<?php
/**
 * Copyright © TrackStreet, Inc. All rights reserved.
 * 
 * @var \TrackStreet\Core\Block\View $block
 */
?>
<?php if ($block->getSettings()->isEnabled() && $block->getSettings()->getCampaignUuid()): ?>

<!-- Begin Reverb integration code -->
<script type="text/javascript">

var _reverbq = _reverbq || [];

_reverbq.push(['init', {
    campaign_uuid: '<?php echo $block->escapeHtml($block->getSettings()->getCampaignUuid()); ?>',
    server: '<?php echo $block->escapeUrl($block->getSettings()->getWidgetServerUrl()); ?>'
}]);

var _reverb_customer_details = {
    <?php if ($block->isLoggedIn()): ?>
        <?php if ($block->getCustomerEmail() !== '' && !empty($block->getCustomerEmail())): ?>email: '<?php echo $block->escapeHtml($block->getCustomerEmail()); ?>',<?php endif; ?>
        <?php if ($block->getCustomerFirstName() !== '' && !empty($block->getCustomerFirstName())): ?>first_name: '<?php echo $block->escapeHtml($block->getCustomerFirstName()); ?>',<?php endif; ?>
        <?php if ($block->getCustomerLastName() !== '' && !empty($block->getCustomerLastName())): ?>last_name: '<?php echo $block->escapeHtml($block->getCustomerLastName()); ?>',<?php endif; ?>
        <?php if ($block->getCustomerPhoneNumber() !== '' && !empty($block->getCustomerPhoneNumber())): ?>phone_number: '<?php echo $block->escapeHtml($block->getCustomerPhoneNumber()); ?>',<?php endif; ?>
    <?php endif; ?>
    campaign_uuid: '<?php echo $block->escapeHtml($block->getSettings()->getCampaignUuid()); ?>',
    iframe: {width: '100%', height: '700px'},
    responsive: true,
};

_reverbq.push(['customer_page', _reverb_customer_details]);

</script>
<script src="<?php echo $block->escapeUrl($block->getSettings()->getScriptUrl()); ?>" type="text/javascript"></script>
<!-- End Reverb integration code -->

<?php endif; ?>